### ISSUE TITLE
Fork 版发布相关讨论

### ISSUE THREAD

**Issue by mytharcher** [yncoder/element-react#1]
由于发布最终基于 npm，所以要改发布的包名。现在有两种方案：

1. 沿用原有包名，使用`@yncoder`组织的 scope 前缀发布为`@yncoder/element-react`。需要在 npm 上注册组织账号并添加开发者。
2. 改新的包名，例如：`whatever-ebue-react`，由 npm 个人账号和其他 collaborator 一起维护。需要确定一个名字（又到了头疼的命名问题）。

所以先个投票吧，回复你希望的方案，选 2 的加上你推荐的包名，回复中点赞最多的胜出。

**Comment by el-psy-k** [comment]
方案2 baolement-react

**Comment by ghost** [comment]
方案2 ele-react

**Comment by mytharcher** [comment]
我个人还是倾向于方案 1。虽然我也可以帮起一堆名字：`ebue`、`baole`、`imfull`……

**Comment by danielliao11** [comment]
chengduole-react

**Comment by pengzekuan** [comment]
yncode/react-ui

**Comment by mytharcher** [comment]
稍微 seriously 来说，这是 fork 别人写的库，而不是完全的重写，那么就不建议太过于恶搞性质的命名。而使用 `@scope/` 方式的命名最大的好处就是能表达这个库的历史渊源，也不会产生冲突。所以还是郑重的提议使用方案 1 `@yncoder/element-react` 作为 npm 的名称，请各位考虑。

**Comment by mytharcher** [comment]
这个问题拖的时间太长了，目前我先以`yncoder-master`为命名分支先启动了，需要其他命名方案的可以自己创建分支对应自由发包。

本仓库主要解决 bug fix 的问题，其他性质的修复或改进不承诺处理。分支协作规划如下：

* `master`：所有 bug fix 都通过 PR 合并到此分支，作为任何命名空间使用的基线版本，但此分支不修改原始包名；
* `yncoder-master`：以`@yncoder/element-react`修改包名的分支，仅合并`master`内容作为 npm 发布使用，不在分支上做任何修改性质的提交；
* `issue-*`：对应已提出的问题的修改分支，用于向`master`发起 PR 的临时分支，亦可以该分支向 eleme 原始仓库提交 PR。
* 所有修改过命名的分支禁止合并到其他分支；

其他需要不同 npm 命名的可以自由定义，仓库不做限制。
